spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb+srv://ecom_user:ecom_pass123@cluster0.bfgmvla.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ecom_db_user

server:
  port: 8082
