spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecom_db_product}
    username: ${DB_USERNAME:ecom_user}
    password: ${DB_PASSWORD:ecom_pass123}
#    url: ${DB_URL:jdbc:postgresql://ep-still-waterfall-a247ccu8-pooler.eu-central-1.aws.neon.tech/ecom_db_product?sslmode=require}
#    username: ${DB_USERNAME:ecom_user}
#    password: ${DB_PASSWORD:npg_YTQ39eokDngt}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
