spring:
  application:
    name: order
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecom_db_order}
    username: ${DB_USERNAME:ecom_user}
    password: ${DB_PASSWORD:ecom_pass123}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

