spring:
  application:
    name: order-service
  profiles:
    active: ${ACTIVE_PROFILE}

  config:
    import: optional:configserver:http://localhost:8181

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh


server:
  port: 8083
